### ISSUE TITLE
사소한 실수 건의 드립니다

### ISSUE THREAD

**Issue by pracworms** [Startlink/BOJ-Feature-Request#101]
[https://www.acmicpc.net/help/judge](https://www.acmicpc.net/help/judge)

[ 왜 컴파일 에러가 나는지 모르겠어요! ] 항목과
[ 채점 결과가 무슨 뜻이지요? ] 항목 아래부분에

[ 보통 이런 경우는 Visual Studio에서 코딩을 했을 때 생기는 현상입니다. GNU와 Microsoft Visual C++의 차이 떄문에 발생하는 문제인데요, 대표적으로 다음과 같은 이유가 있을 수 있습니다. ]
위와 같은 문장이 중복 작성되어 있습니다.

**Comment by Baekjoon** [comment]
다른 내용으로 모두 수정되었습니다.
