### ISSUE TITLE
맞은 사람 소스보기 기능 추가 문의 

### ISSUE THREAD

**Issue by nhs0912** [Startlink/BOJ-Feature-Request#102]
안녕하세요. 백준 온라인 저지 사용하는 학생입니다. 
다름이 아니라 제 회원정보에는 주언어 자바로 설정을 했는데요.
문제 맞은 사람 소스 보기 할 때 제 주언어가 자동으로 설정되어서 그 주언어에 맞는 순위를 보여주었으면 좋겠습니다.

지금은 탭다운(?)버튼으로 c, c++ ,java 등등으로 골라야하는데요. 그 과정 없이 자동으로요! 
그러면 더 편리한 온라인 저지 사이트가 될 것 같습니다!

**Comment by Baekjoon** [comment]
사람마다 원하는 동작이 다르기 때문에 추가하기 어렵습니다.

예를 들어, C++ 언어의 경우에는  C++, C++11, C++14 모든 언어를 보고싶을 수 있기 때문에, 기본은 전체로 두는 것이 좋다고 생각합니다.
