### ISSUE TITLE
그룹 내에서 연습 만들 때 패널티 시간 수정 가능했으면 해요.

### ISSUE THREAD

**Issue by neinsys** [Startlink/BOJ-Feature-Request#103]
패널티가 틀린 횟수마다 20분으로 기억하는데, 수정 가능해도 좋지 않을까요. 만들때 설정하는 방식으로요.

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
