### ISSUE TITLE
원문과 번역문의 내용이 다를 때 따로 표시를 해 주세요.

### ISSUE THREAD

**Issue by xdoju** [Startlink/BOJ-Feature-Request#104]
https://www.acmicpc.net/board/view/12845 에서 추가해 주신다고 하셨던 기능입니다. 원문을 기본 옵션으로 설정해 놓는 입장에서는 원문을 기준으로 문제를 풀었다가 WA나 RTE를 맞거나 아예 입출력 조건부터 달라서 혼란을 겪는 경우가 있어서 꼭 필요한 기능입니다.

<img width="264" alt="2017-02-21 10 51 12" src="https://cloud.githubusercontent.com/assets/4413599/23147621/bd72a936-f823-11e6-92e9-f1069c54900d.png">
스페셜 저지 문제들처럼 라벨을 붙여 표시하는 건 어떨지 제안해 봅니다.

**Comment by Baekjoon** [comment]
오? 원문과 다름 마크 좋네요 
문구 뭐라고 할지 고민하느라 못 붙이고 있었는데

**Comment by Baekjoon** [comment]
표시했습니다.
