### ISSUE TITLE
그룹 내 채팅기능과 활동 중 표시기능

### ISSUE THREAD

**Issue by ghost** [Startlink/BOJ-Feature-Request#106]
페북에도 있는 활동 중같은 표시창이 있으면 좋겠습니다
밤에 코딩할 때 친구가 활동(코딩) 중인지 확인하려고 카톡을 보내기는 좀 그렇더라고요
그룹내에서는 채팅창기능도 있으면 좋겠습니다

**Comment by nhs0912** [comment]
와 이거 있으면 좋긴하겠네요 ㅋㅋ

**Comment by Baekjoon** [comment]
다른 서비스를 이용해서 대체할 수 있을 것 같습니다.
