### ISSUE TITLE
기능 추가 요청합니다.

### ISSUE THREAD

**Issue by Jaysok** [Startlink/BOJ-Feature-Request#113]
1. 댓글 수정 기능
ㅡ 댓글을 작성하고 나서 수정할 수가 없어서 다소 불편한 것 같습니다.

2. 문제집관련
ㅡ 다른 사람의 문제집을 북마크 할 수 있었으면 좋겠습니다.
ㅡ 문제집을 만들 때 계층을 나눌 수 있었으면 좋겠습니다. ex) [최단경로]-[다익스트라], [최단경로]-[플로이드].

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
