### ISSUE TITLE
상태 메시지 길이 제한이 이상하게 적용됩니다.

### ISSUE THREAD

**Issue by xdoju** [Startlink/BOJ-Feature-Request#114]
경고문에는 최대 100자까지 입력할 수 있다고 되어 있지만 실제로는 100자에 훨씬 못 미치는 메시지를 입력해도 등록이 안 됩니다. 한글이 UTF-8 기준 한 글자당 3바이트를 차지하는 것과 관련이 있어 보입니다.

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
