### ISSUE TITLE
MathJax CDN Provider 변경

### ISSUE THREAD

**Issue by veydpz** [Startlink/BOJ-Feature-Request#116]
BOJ에서 사용하고 있는 `cdn.mathjax.org`가 2017년 05월 02일 부로 닫힌 바, `MathJax.js`의 CDN Provider를 다른 것으로 교체해야 할 것 같습니다.

해당 CDN이 닫힌 후, `cdnjs.cloudflare.com`으로 redirect되고 있어서 현재는 수식 렌더링에 문제가 없습니다. 하지만 잠정적 피해를 막기 위해 BOJ에서 사용되는 MathJax CDN을 `cdn.mathjax.org`이 아닌 `cdnjs.cloudflare.com` 등으로 교체하면 좋을 것 같습니다.

자세한 내용은 https://www.mathjax.org/cdn-shutting-down/ 에 나와 있습니다.

감사합니다.

**Comment by Baekjoon** [comment]
변경했습니다.
