### ISSUE TITLE
다른 사람의 소스를 읽었을 때 그사람에게 알림이 뜨는 기능

### ISSUE THREAD

**Issue by sgc109** [Startlink/BOJ-Feature-Request#117]
다른 사람의 소스를 읽었을 때 그사람에게 알림이 뜨는 기능이 굳이 필요한 기능인지 궁금합니다.
굳이 필요한 것이 아니라면 없애는게 좋지않을까 조심스레 건의해봅니다.
다른 사람의 소스코드를 읽는 사람이 좀더 부담없이 편하게 마음껏 열어볼 수 있는게 낫지않을까하는 마음에서 입니다. 소스 코드를 읽는 사람은 그냥 어떤 사람의 소스코드가 궁금해서 계속해서 열어볼 수가 있는 것인데 그 알림을 받는 사람 입장에서는 알림이 많이 떠있으면 그 사람의 의도와 생각과는 다르게 받아 들여질 수도 있다고 생각합니다.

**Comment by Baekjoon** [comment]
설정에서 알림 끌 수 있습니다.
