### ISSUE TITLE
맞왜틀 도움을 위한, 틀린 testcase 유료구매 기능 또는 유저의 예시 입력 추가 기능

### ISSUE THREAD

**Issue by OoO256** [Startlink/BOJ-Feature-Request#119]
BOJ 질문게시판에서 가장 많은 비중을 차지하는 상황은 "예제는 다 맞는데 x퍼센트에서 틀렸습니다. 아무리 고민해봐도 이유를 모르겠습니다."류의 상황입니다.
이 경우 본인이 그 소스의 반례를 찾아내는 것은 어렵고 답답한 과정 입니다.

그래서 본인이 틀린 testcase를 유료로라도 알아낼 수 있었으면 좋겠습니다.

최근 BOJ사이트의 수익성 확보를 위해 여러가지 기능을 추가하고 있는 것으로 아는데 이 기능을 추가하면 BOJ의 수익구조 또한 개선할 수 있을 것이라고 생각합니다. 보통 문제를 푸는 사람은 '내 방법이 왜 틀렸는지'를, '다른 풀이는 무었인지'보다 더 많이 궁금해 한다는 점을 근거로 볼 때, 기존의 '풀이'기능보다 더 활성화될 수 있는 기능이라고 생각합니다. 

위 기능의 구현이 어렵다면, 차선으로 유저들이 예시 입력을 추가할 수 있었으면 좋겠습니다. 
위와 같은 상황을 주로 만드는 문제를 풀 때 주의해야 할 반례는 이전에 문제를 푼 사람들도 비슷한 어려움을 주었을 확률이 높을거라고 생각합니다. 
그래서 먼저 반례를 인지하고 문제를 해결한 사람이 그 문제에 그 예시 입력을 추가한다면, 그 반례로 고통받는 사람은 앞서 유저들이 추가한 '추가 예제'를 열람하고, 본인의 문제 해결이 어느 반례를 포함하지 않는지 쉽게 알 수 있을 것입니다.

**Comment by YoungJaeChoung** [comment]
저도 이 기능이 너무나 필요합니다. 

추가로 선생님 플랫폼이 되어서, 해당 문제에서 무엇을 잘못 했는지에 대해서 
유료로 해결받을 수 있으면 좋을 것 같습니다.

**Comment by Baekjoon** [comment]
이 기능은 제공하지 않습니다.
