### ISSUE TITLE
그룹 메인에 2년만에 게시판을 만듬.. 로그 삭제해주세요!

### ISSUE THREAD

**Issue by CodeSang** [Startlink/BOJ-Feature-Request#12]
그룹 메인에 2년만에 게시판을 만듬.. 로그 삭제해주세요!

의미가 있다면 죄송합니다!!

**Comment by Baekjoon** [comment]
로그가 아니고... 진짜 2년만에 만들어서 그렇게 써놓았습니다.

메인에 뭘 넣어야 좋을까요?

**Comment by Baekjoon** [comment]
삭제 하고 무엇을 넣으면 좋을까요로 바꿨습니다.
