### ISSUE TITLE
그룹내 문제집 위치 옮기기

### ISSUE THREAD

**Issue by dlsvltk** [Startlink/BOJ-Feature-Request#122]
문제집 내부에 있는 문제들 위치를 바꿀수 있듯이 그룹내 문제집 위치도 마찬가지로 옮겨졌으면 합니다.!!!
현재로써는 문제집 위치를 수정하기 위해서는 CLEAR시킨 다음에 새로 넣는 방법밖에 없어서요...

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
