### ISSUE TITLE
질문에 코인을 걸 수 있는 기능

### ISSUE THREAD

**Issue by OoO256** [Startlink/BOJ-Feature-Request#124]
문제를 풀다가 도저히 왜 틀리는지 모르겠어서 제 코드를 복사해서 질문글을 올린 적이 많습니다.
하지만 남이 쓴 코드를 읽고 이해하고 틀린 원인을 분석하는 것은 많은 노력을 필요로 하는 일 이라서 이러한 질문글에는 답이 잘 달리지 않습니다. 이런 질문글에 네이버 지식 인 서비스처럼 코인을 걸고 체택된 답변에 코인을 주는 기능을 만들면 질문의 답변을 구하기가 훨씬 수월해지고, 답변하는 분은 노동에 대한 보상을 받을 수 있습니다.

혹시 코인은 BOJ내에서만 사용할 수 있기 때문에 답변을 하는 것에 대한 유인이 부족하다고 생각되면, 일정량의 코인을 모으면 상품과 교환할 수 있는 시스템을 만들어도 좋을 것 같습니다.
BOJ 스티커 50코인
호식이 두마리 치킨 500코인
이런 식으로요.

**Comment by Baekjoon** [comment]
제공하지 않을 기능입니다.
