### ISSUE TITLE
랭킹 차트 / 상위몇% / 하루에 몇문제 푼지 차트

### ISSUE THREAD

**Issue by wnghdcjfe** [Startlink/BOJ-Feature-Request#127]
를 구현 해주면 좋을 것같아요!
USER당 날짜 / 랭킹 이런식 TABLE을 만들어서 차트로 구현해서, 랭킹이 내가 이날 이렇게 오르는구나 라는 걸 알았으면 좋겠어요!
그리고 내가 상위 몇퍼센트인지도..요!ㅎㅎㅎ
그리고.. 날짜/ 몇문제 이런식으로 해서 몇문제를 풀었는지를 알면 좀 뿌듯할 것같아요. 

D3를 통해서 하면 될 것같은데.. 도움이 필요하시면 제가 DB부분연결부분을 제외하고 같이 만들 수도 있습니다! (사실 같이 만들고싶은..!)

**Comment by MoonHyuk** [comment]
하루에 얼마나 풀었는지는 간단하게 https://acmicpc.cc 에서 확인하실 수 있습니다.

**Comment by wnghdcjfe** [comment]
앗 갔다왔어요 그 사이트
근데 음 이거말구 제가 원하는 건 다른 형태인데...
제가 한번 만들어서 보여드릴개욥ㅎㅎ

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
