### ISSUE TITLE
nodejs 업그레이드 부탁드립니다.

### ISSUE THREAD

**Issue by ynifamily3** [Startlink/BOJ-Feature-Request#128]
ES6 문법 쓰고 싶어요..

**Comment by kyunghyunso** [comment]
저도 부탁드려요!!! 흑흑흑 ㅠ푸ㅠㅜ

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
