### ISSUE TITLE
유저에 대한 통계에 문제 분류에 대한 비율도 나오면 좋겠습니다

### ISSUE THREAD

**Issue by rnaster** [Startlink/BOJ-Feature-Request#132]
상위 랭커분들은 어떤 비율로 문제를 풀고 계신지 궁금합니다.
DP, DFS, BFS 등을 원 그래프로 나타나면 좋을 것 같습니다..!

**Comment by Baekjoon** [comment]
안녕하세요.

현재는 solved.ac 에서 이를 지원하고 있습니다.

감사합니다.
