### ISSUE TITLE
커밋 메시지 처럼 제출 할 때 간단한 메시지 남길 수 있게 했으면 좋을 것 같아요.

### ISSUE THREAD

**Issue by JulyLeaver** [Startlink/BOJ-Feature-Request#134]
코드 제출할때 간단한 메시지 남길 수 있으면 좋을 것 같아요.
커밋 할때 메시지 작성하는 것처럼요.

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
