### ISSUE TITLE
음성 채팅방

### ISSUE THREAD

**Issue by JaeHyun0227** [Startlink/BOJ-Feature-Request#136]
아주 무리가 큰 부탁이긴 하지만, 
코딩에 대해 질문하고 회의할 수 있는 음성 채팅방이 있으면 좋겠습니다.

ex) 스카이프,토크온, **디스코드**

**Comment by Baekjoon** [comment]
굳이 음성 채팅방이 필요한지는 모르겠습니다.

이미 *슬랙*이 있습니다.
