### ISSUE TITLE
Clojure 1.9 런타임 에러 문제

### ISSUE THREAD

**Issue by MShrimp4** [Startlink/BOJ-Feature-Request#138]
Clojure 1.9부터 몇몇 라이브러리들이 *.alpha 네임스페이스로 변경되어서인지 런타임 에러가 납니다. 그 중에는 def같은 기본적인 것도 있는 듯 한데, [https://groups.google.com/d/msg/clojure/10dbF7w2IQo/WlIX82ByAwAJ](https://groups.google.com/d/msg/clojure/10dbF7w2IQo/WlIX82ByAwAJ) 에서 보면 백준 서버와 같이 1.9에서 java -cp clojure.jar clojure.main Main.clj 로 클로저를 실행할 경우 정상적으로 작동하지 않는다고 합니다. 그러므로

1. 서버 옵션에서 Clojure 1.8 옵션을 지원
2. Clojure 1.9의 런타임 에러 해결

둘 중 하나는 해주셨으면 좋겠습니다. 1번은 기존의 인자로 정상 실행되니 참고하시길 바랍니다.

**Comment by Baekjoon** [comment]
안녕하세요.

1. Clojure 1.8로 다시 내리겠습니다.
