### ISSUE TITLE
게시판의 소스가 어느 언어인지 확인할 수 있게 해주세요

### ISSUE THREAD

**Issue by BupjaeLee** [Startlink/BOJ-Feature-Request#139]
![which_language](https://user-images.githubusercontent.com/1683826/38415275-fa244bf6-39cb-11e8-98d8-460b0cebc726.png)

특히 프로그램 길이가 짧을 경우 어느 언어로 되어있는지 알기 힘듭니다.

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
