### ISSUE TITLE
문제마다 메모를 남길 수 있는 기능

### ISSUE THREAD

**Issue by ntopia** [Startlink/BOJ-Feature-Request#14]
내가 이 문제를 이러이러케 풀었다 혹은
이러이러케 시도했는데 못풀었다 등등
짤막한 메모를 남길 수 있는 기능
그리고 그 메모가 검색까지 된다면 정말 좋겠어요!

**Comment by ntopia** [comment]
다른 사람의 메모를 읽어보는 것도 재밌을 것 같단 생각이 드네요.
공개한 메모에 한해서 다른 유저들이 어떤 메모를 남겼는지 보여주는 것도 가능하면 좋겠습니다.

**Comment by Baekjoon** [comment]
추가 됨

및

검색 업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
