### ISSUE TITLE
닉네임 기능을 추가해주세요.

### ISSUE THREAD

**Issue by VertexToEdge** [Startlink/BOJ-Feature-Request#141]
랭킹이나 그룹에서 아이디만으로 누가 누군지 알아보기 힘든 점이 없지않아 있습니다.
닉네임을 통해 자신만의 개성을 나타낼 수 있었으면 좋겠습니다.

**Comment by Baekjoon** [comment]
안녕하세요.

2022년 내로 사이트의 아이디 시스템을 버리고 닉네임 제도로 가기 위해서 준비하고 있습니다.

의견 남겨주셔서 감사합니다.
