### ISSUE TITLE
solarized 테마가 이상해요.

### ISSUE THREAD

**Issue by sohnryang** [Startlink/BOJ-Feature-Request#142]
분명 제가 아는 건 이랬는데...

<http://ethanschoonover.com/solarized>

**Comment by Baekjoon** [comment]
CodeMirror에서 그런 식으로 제공하는 것 같습니다.

**Comment by sohnryang** [comment]
글쎄요... [코드미러 데모](https://codemirror.net/demo/theme.html#solarized%20dark)에서 잘 보이는것 같은데요

**Comment by Baekjoon** [comment]
그럼 확인해보겠습니다.

**Comment by Baekjoon** [comment]
수정되었습니다.

**Comment by sohnryang** [comment]
:dhk: 감사합니다
