### ISSUE TITLE
[언어 추가 요청] Assembler (MIPS / SPIM) 을 추가해 주세요

### ISSUE THREAD

**Issue by BupjaeLee** [Startlink/BOJ-Feature-Request#145]
교육용으로 어셈블리 언어를 배울 때 많이 사용하는 플랫폼으로 알고 있습니다.

**Comment by BupjaeLee** [comment]
SPIM 은 (교육용) MIPS 에물레이터의 이름입니다
입출력 및 동적 메모리 할당 등은 syscall 명령어를 사용합니다.

http://spimsimulator.sourceforge.net

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
