### ISSUE TITLE
페이지마다 타이틀 구분이 명확해지면 좋겠습니다

### ISSUE THREAD

**Issue by debug-log** [Startlink/BOJ-Feature-Request#149]
1. 소스코드 페이지 타이틀

예시
* 소스코드 번호 : 105348732번
* 문제를 푼 사람 : startlink
* 문제번호 : 12388번

현재 타이틀 : 105348732번 소스 코드
변경 후 타이틀 : startlink님의 12388번 풀이

안녕하세요.
BOJ에서 문제풀이를 하다보면 한 브라우저에 탭을 여러개 띄워 놓고 여러 사람들의 소스 코드를 켜놓곤 합니다.
그런데 지금 소스코드의 타이틀은 너무 알아보기 어렵습니다.
타이틀에 105348732번이라는 숫자는 사실 유저에게는 큰 의미가 없는 숫자이며, 여러 탭이 켜져 있을 경우 서로 구분하기가 너무 불편합니다.

2. 채점 현황 타이틀
https://www.acmicpc.net/status?user_id=startlink&result_id=4
https://www.acmicpc.net/status?from_problem=1&problem_id=11729
https://www.acmicpc.net/status?group_id=212345

위와 같이 '채점 현황'이란 타이틀을 갖고 있는 페이지마다 종류가 무척 다양합니다.
유저별, 문제별, 그룹별 등 각자 다른 성격을 갖고 있음에도 불구하고 타이틀이 모두 같아 헷갈리기 쉽습니다.

각각,
startlink님 채점현황
11729번 문제 채점현황
xxxx그룹 채점현황

등으로 변경되면 좋을 것 같습니다.

**Comment by Baekjoon** [comment]
안녕하세요.

문제 번호는 문제를 대신해서 대표값으로 말하기도 하지만, 소스 코드의 제출 번호는 그렇게 사용되지는 않습니다. 말씀하신 것 처럼 소스 코드를 보는 페이지의 페이지 타이틀에 제출 번호를 넣는 것은 크게 의미가 없을 수도 있습니다. 여러가지 방안을 생각해서 다음 업데이트에서 준비해보겠습니다.

채점 현황의 경우 다양한 검색 옵션이 있고, 이를 페이지 타이틀에 보여주는 것은 좋을 것 같습니다. 많은 옵션이 있어서 복잡할 것 같지만, 한 번 시도해보겠습니다.

의견 남겨주셔서 감사합니다.
