### ISSUE TITLE
루비 파생언어인 크리스탈언어도 추가해주세요 !!!!!!!!!!

### ISSUE THREAD

**Issue by ghost** [Startlink/BOJ-Feature-Request#150]
맨날 루비 성능이느려서 틀린건지 루비가 느린건지 알수가없어서 보니까 ruby 문법과 똑같으면서 속도는  c언어처럼빠른 크리스탈언어를 발견해서 부탁합니다.

크리스탈언어추가해주세요 ㅠㅜ

**Comment by Baekjoon** [comment]
안녕하세요.

Crystal을 BOJ에 추가했으나, 현재 채점 프로그램과 호환이 잘 되고 있지 않습니다.

다음 채점 프로그램 업데이트 때 다시 테스트해보겠습니다.

감사합니다.
