### ISSUE TITLE
Rust 최신 버전 지원

### ISSUE THREAD

**Issue by doohochang** [Startlink/BOJ-Feature-Request#154]
Rust 2018이 반영된 최신버전인 1.32.0으로 업데이트 요청드립니다!

**Comment by tirr-c** [comment]
현재 최신 버전은 1.33.0입니다.

1.30.1과 비교했을 때 많은 변경점이 있는데, 온라인 저지에 영향을 줄 만한 점은 두 가지가 있습니다.

* **2018 edition 추가**: 기존의 2015 edition과 비교했을 때 몇 가지 breaking change를 포함한 2018 edition의 지원이 1.31.0에서 추가되었습니다. C++11과 C++14의 차이와 비슷합니다(엄밀히 따지면 좀 다릅니다). 컴파일러 기본값은 2015이며 `rustc --edition 2018`으로 활성화할 수 있습니다.
  - 2018 edition을 별도의 컴파일러로 취급해야 할 것 같습니다. 재채점하면 컴파일되던 코드가 컴파일되지 않을 수 있으니까요.
* **기본 할당자 변경**: Rust는 1.31.1까지 할당자로 jemalloc을 썼기 때문에 기본 메모리 사용량이 많이 높았습니다. 1.32.0에서 할당자가 시스템 할당자로 바뀌어, 기본 메모리 사용량이 크게 줄었습니다.

**Comment by Kroisse** [comment]
덧붙여서, 에디션은 버전과는 개념이 달라서 최신 버전인 1.33을 포함해서 앞으로 나올 컴파일러도 2018 에디션과 함께 2015 에디션도 계속 지원하게 됩니다. 때문에 2018 에디션을 추가하는 것과 별개로 기존의 Rust(2015 에디션) 컴파일러 버전도 함께 최신으로 업데이트하는 편이 좋을 것이라고 생각합니다.

**Comment by Baekjoon** [comment]
제가 Rust를 사용하질 않아 잘 모르는 내용인데, 자세하게 설명해주셔서 감사합니다.

Rust 2018을 추가하고, rustc의 버전을 업했습니다.

https://www.acmicpc.net/board/view/34715
