### ISSUE TITLE
node.js 최신 버전 지원

### ISSUE THREAD

**Issue by disjukr** [Startlink/BOJ-Feature-Request#155]
현재 node.js 최신 안정 버전인 `11.10.1`으로 판올림 부탁드립니다.

**Comment by NoMoreViolence** [comment]
nodejs는 짝수 버전에 대해서 LTS를 제공하니, 10.x.x 버전대로 지원을 해 주시는 것이 더 좋지 않을까요?
@disjukr

**Comment by Baekjoon** [comment]
node.js은 업데이트 계획이 없습니다.

**Comment by disjukr** [comment]
@Baekjoon 업데이트 계획이 없는 이유를 알 수 있을까요?
앞으로 지원 계획이 영영 없는 것인지, 아니면 당장은 다른 중요한 일들에 우선순위가 밀리는 것인지 궁금합니다.

**Comment by wan2land** [comment]
@Baekjoon

언어 정보(https://www.acmicpc.net/help/language)를 보니 대부분 다른언어들은 2018년쯤 판올림을 한 것 같은데 node.js 만 업데이트 계획이 없는 이유를 알고 싶습니다.

**Comment by Baekjoon** [comment]
현재 사용하는 버전보다 높은 버전은 채점 프로그램과 호환이 안되어서 업데이트 계획이 없습니다.

**Comment by Baekjoon** [comment]
downvote와 confused를 누르신 많은 여러분

downvote를 upvote로 올릴 수 있는 가능성을 발견했습니다.

오늘 우연히 생각이나서 코딩을 했는데, node v10.16.0의 채점에 성공했습니다.

`/dev/stdin` 에 접근하지 못하는 문제만 해결하면 node도 드디어 올림이 될 것 같습니다.

다른 언어에서 사용하는 방식을 사용해도 `/dev/stdin`에 접근하지 못해 이 문제만 해결하면 될 것 같습니다.

**Comment by Baekjoon** [comment]
https://www.acmicpc.net/board/view/38244

**Comment by disjukr** [comment]
현재 최신 안정 버전은 `12.5.0`인 상태이고 12 버전대는 LTS 지원이 될 예정이니 가능하다면 `12.x` 버전으로 지원이 되었으면 좋겠습니다.

**Comment by Baekjoon** [comment]
보통 한 언어가 버전이 올라가서 채점 불가능에서 채점가능으로 변경이 되면 그 이후 버전은 채점이 계속 가능했었습니다.

v10.16이 성공하면 v12도 아마 가능할 것이라 예상합니다.

**Comment by Baekjoon** [comment]
node.js의 채점 지원 역사는 참 고난의 연속이었습니다.

만약 성공하면 블로그에 글을 남겨봐야 겠습니다. 소스 컴파일도 몇 번이나 했는지 알 수가 없군요.

**Comment by wan2land** [comment]
함께 문제해결해보고 싶습니다. 내부에서 어떤식으로 구현되어있는지 설명해주실 수 있을까요? :-)

**Comment by Baekjoon** [comment]
내부 구현을 설명하면 다른 쪽에 무슨 부작용이 있을지 몰라 일단은 공개하지 않으려고 합니다. 

기존에 제출된 소스가 /dev/stdin 을 읽고, 대다수 구현이 이런식으로 되어 있어서 일단 우선적으로 해결해보려고 합니다. 

말씀해주신 장식도 잘 되는지 확인해보겠습니다.

**Comment by Baekjoon** [comment]
node.js v10.16.0으로 업데이트 되었습니다.

https://www.acmicpc.net/board/view/38673
