### ISSUE TITLE
소스 코드 공개 설정을 한꺼번에 수정할 수 있게 해주세요

### ISSUE THREAD

**Issue by jaehoo1** [Startlink/BOJ-Feature-Request#159]
![image](https://user-images.githubusercontent.com/44667299/65129231-d9942f80-da35-11e9-8964-0acf040c06b3.png)
현재 BOJ에서 소스 코드 공개 설정을 변경하면, 변경 전에 제출했던 소스 코드들의 공개 설정은 바뀌지 않고, 이후의 설정들만 바뀝니다. 자신이 제출한 코드 전부의 공개 설정을 한꺼번에 바꿀 수 있는 기능이 생겼으면 좋겠어요

**Comment by Baekjoon** [comment]
안녕하세요.

현재는 기존 코드의 공개 설정을 수정하려면 모든 소스를 하나씩 열어서 바꿔야 합니다. 이전에 제출한 소스의 공개 설정을 일괄로 바꾸는 것은 과거에는 있었으나 현재는 사라진 기능입니다.

왜 사라졌는지는 잘 모르겠지만 있는 것이 훨씬 더 의미있고 편할 것이라 생각되어 다음 업데이트에 이를 추가해보겠습니다.

감사합니다.
