### ISSUE TITLE
Codeforces 레이팅과 동기화되는 색깔을 보다 더 정확하게 바꿔주세요.

### ISSUE THREAD

**Issue by aahcbird** [Startlink/BOJ-Feature-Request#161]
적록색약 사용자들을 위해 BOJ 아이디 색이 Codeforces 닉네임의 색과 정확히 일치하도록 변경해주세요.

특히 Cyan과 Purple 등급의 색이 거의 구분되지 않습니다.<br><br>

---
* BOJ의 Cyan =
R : 3, G : 168, B : 158

* Codeforces의 Cyan = 
R : 119, G : 221, B : 187
---

* BOJ의 Purple =
R : 170, G : 0, B : 170

* Codeforces의 Purple = 
R : 255, G : 136, B : 255

**Comment by Baekjoon** [comment]
예전에 코드포스 추가할때랑 지금 색이 다른가봅니다.

**Comment by Baekjoon** [comment]
현재 BOJ의 색과 코드 포스의 색이 일치하고 있는데, 위에서 언급한 레퍼런스는 어디인가요.

* https://ddo7jzca0m2vt.cloudfront.net/css/connect.css
* https://sta.codeforces.com/s/65976/css/community.css

**Comment by aahcbird** [comment]
죄송합니다. 착오가 있었습니다.
