### ISSUE TITLE
언어 즐겨찾기 기능을 추가해 주세요

### ISSUE THREAD

**Issue by sohnryang** [Startlink/BOJ-Feature-Request#163]
현재는 사용할 언어 하나만 설정할 수 있는데, 아래에 제가 대충 그린 그림처럼 언어 선택할때 즐겨찾기로 선택한 언어가 상위에 있으면 좋을 것 같습니다.
<img width="305" alt="language-select" src="https://user-images.githubusercontent.com/15506585/67910990-30119380-fbc8-11e9-9064-c23c5b26248b.png">

**Comment by Baekjoon** [comment]
https://github.com/Startlink/update-note/blob/master/boj-todo.md

예정되어 있습니다.

**Comment by sohnryang** [comment]
아 그렇군요
