### ISSUE TITLE
Jelly Language를 추가해 주세요.

### ISSUE THREAD

**Issue by buttercrab** [Startlink/BOJ-Feature-Request#164]
[Jelly Language](https://github.com/DennisMitchell/jellylanguage)를 추가해 주세요.

이 언어는 숏코딩을 위해 특별히 고안된 언어입니다. 

또한 이 언어의 특징은 1바이트에 128개가 모두 기능이 할당되어 있는데, 이를 볼 수 있게 유니코드로 주로 씁니다. 그래서 입력은 유니코드로 받되, 소스코드 길이는 한 문자당 1바이트로 설정해 주시는 것을 요청합니다.

백준 1000번 소스 코드는 다음과 같습니다. 
```
+
```

**Comment by Baekjoon** [comment]
안녕하세요.

다양한 언어가 추가되고 있는 BOJ인 만큼 이런 언어가 추가되는 것도 좋을 것 같습니다.

다음 업데이트 때 Jelly Language의 추가를 시도해보겠습니다.

의견 남겨주셔서 감사합니다.
