### ISSUE TITLE
Julia 언어 추가 요청합니다

### ISSUE THREAD

**Issue by seastar105** [Startlink/BOJ-Feature-Request#168]
예전 dockerfile 레포를 보니 예전에 추가계획이 있었던거 같은데 계획이 취소되었나보네요
1.0.5 LTS 버전으로 추가 요청합니다

**Comment by Baekjoon** [comment]
안녕하세요.

Julia는 추가하려고 노력 중이나 현재 채점 프로그램과 호환이 되지 않습니다.

추후에 채점 프로그램 업데이트 때 다시 확인해보겠습니다.

감사합니다.
