### ISSUE TITLE
favicon으로 정답 여부 확인하는 기능 추가해주세요

### ISSUE THREAD

**Issue by sohnryang** [Startlink/BOJ-Feature-Request#171]
Travis CI같은 사이트에서는 빌드 진행중/성공/실패를 favicon 색깔으로 구분해서 보여줍니다.

백준 채점 현황 페이지에서도 이런 기능을 추가하면 좋을 것 같습니다. 채점 중인 경우에는 favicon이 노란색, 맞았으면 초록색, 틀렸습니다/시간초과/런타임에러 같은거 뜨면 빨간색으로요

**Comment by Baekjoon** [comment]
채점 현황에는 수많은 결과가 있기 때문에, 어려울 것 같습니다.

**Comment by sohnryang** [comment]
간단하게 실패에는 빨간색, 성공에는 초록색 정도만 해도 되지 않을까요?

**Comment by Baekjoon** [comment]
채점 현황에 결과가 하나만 있지 않습니다.
