### ISSUE TITLE
2900번 문제에서 코드가 사라지는 버그가 있습니다.

### ISSUE THREAD

**Issue by EatChangmyeong** [Startlink/BOJ-Feature-Request#172]
<https://icpc.me/2900>에서 문제 언어를 영어로 바꿨다가 도로 한국어로 바꾸면 '아래 something 함수를 호출한다.' 아래에 표시되어야 할 코드가 표시되지 않습니다.

**Comment by Baekjoon** [comment]
안녕하세요.

오래 전 SyntaxHighlighter를 사용할 때 있던 버그입니다. 현재는 이 라이브러리를 사용하지 않아서 화면에 잘 보이고 있습니다.

버그 제보주셔서 감사합니다.
