### ISSUE TITLE
문제집 연속 풀기

### ISSUE THREAD

**Issue by jye326** [Startlink/BOJ-Feature-Request#176]
그룹에서 문제집을 생성하여 순차적으로 풀어나가는데, 문제 하나를 풀고 나면 해당 문제집의 다음 문제로 링크되는 버튼 등이 있으면 좋겠습니다. 현재는 다음 문제까지 가는 데에 5번의 클릭이 필요합니다.

**Comment by Baekjoon** [comment]
안녕하세요.

그룹 내에서 문제집, 연습 등의 기능이 단순 링크의 효과밖에 되지 않아서 새 탭을 띄우지 않는다면 다른 문제를 풀기 불편할 것 같습니다.

그룹의 업데이트를 계속해서 준비하고 있는데, 말씀하신 것과 같은 편의를 위한 기능도 준비하겠습니다.

감사합니다.
