### ISSUE TITLE
코드 컴파일기능과 오류내역, 오류 라인을 볼수있게 추가해주세요

### ISSUE THREAD

**Issue by Atlasias** [Startlink/BOJ-Feature-Request#180]
1. 컴파일 테스트 기능
2. 오류 발생 줄 혹은 오류 내용을 확인할 수 있게 해주세요

**Comment by Baekjoon** [comment]
채점 현황에서 컴파일 에러를 클릭하면 컴파일 에러 내용을 볼 수 있습니다.
