### ISSUE TITLE
언어별로 문제 다르게 취급

### ISSUE THREAD

**Issue by commonstyle** [Startlink/BOJ-Feature-Request#182]
설정에서 언어를 선택하고 C언어로 A문제를 풀었을 때 C언어 설정 상태에서는 풀었다고 나오고 node.js로 설정하고 A문제을 들어가면 풀지 않았다고 나오게 하면 좋을듯

**Comment by Baekjoon** [comment]
안녕하세요.

시즌 모드와 언어 모드라는 2가지 모드를 준비하고 있는데, 여기서 언어 모드가 말씀하신 것과 동일한 모드입니다.

아직은 공개하기까지 갈 길이 멀지만 빠른 시일 내에 공개해보겠습니다.

의견 남겨주셔서 감사합니다.
