### ISSUE TITLE
사이버지식정보방에서 무한 로그인 현상을 해결해주세요

### ISSUE THREAD

**Issue by tmdtrash** [Startlink/BOJ-Feature-Request#183]
ㅠㅠ 코딩공부를 하고싶은 군인입니다
사이버 지식정보방에서 코딩을 하고싶은데
로그인이 안됩니다
구글이나 네이버 로그인은 되는데 백준은
한 20번 넘게 시도하면 한번정도 로그인이됩니다
그 이외에는 로그인 중... 이라는 표시만 뜨고 로그인이 안됩니다
혹시 제가 조치해서 해결할 수 있는 방법이라던가 다른방법을 알려주시면 감사하겠습니다

**Comment by Baekjoon** [comment]
안녕하세요.

사이트 이용에 불편을 드려서 죄송합니다. 댓글을 늦게 달았는데, 현재는 해결된 것으로 알고 있습니다.

감사합니다.
