### ISSUE TITLE
언어 중 C# 6.0의 이름을 C# 7.0으로 바꾸는 것이 좋을 듯 합니다.

### ISSUE THREAD

**Issue by pid011** [Startlink/BOJ-Feature-Request#185]
https://www.mono-project.com/docs/about-mono/languages/csharp/

해당 페이지의 설명을 보면 C# 7의 일부 문법을 지원한다고 나와 있습니다.

실제로 테스트 해본 결과 로컬 함수를 제외하면 7.0 문법까지는 거의 다 정상적으로 컴파일됩니다.

**Comment by Baekjoon** [comment]
C# 9.0 (.NET)이 추가되었습니다. C# 6.0은 C# 6.0 (Mono)로 놔두었고, 그대로 놔둬도 될 것 같습니다.
