### ISSUE TITLE
자신의 코드가 어떤 반례에서 틀리는 지 현상금을 걸 수 있는 기능

### ISSUE THREAD

**Issue by jsrimr** [Startlink/BOJ-Feature-Request#187]
자신의 코드가 어떤 테스트 케이스 때문에 통과하지 못하는지 답답할 때가 많습니다. 게시판에 도움을 요청해도 답이 없을 때가 많고 답이 오더라도 오래걸리는 경우가 많은데요, 답변을 하기 위해서는 많은 시간이 들기 때문이라고 생각합니다. 따라서, 답변을 해주는 사람도 시간을 들여 답을 해주는 만큼 그에 대한 보상책을 제공할 수 있게 하면 좋을 것 같습니다. 이를 통해 질문자도 더 퀄리티 있는 답을 빠른 시간안에 얻을 수 있고 답변자도 금전적 이득을 얻을 수 있습니다.

**Comment by Baekjoon** [comment]
안녕하세요.

현재는 게시판에서 보상을 주거나 현상금을 거는 등의 기능은 계획되어 있지 않습니다.

의견 남겨주셔서 감사합니다.
