### ISSUE TITLE
틀린 데이터 확인

### ISSUE THREAD

**Issue by rkdrjs0327** [Startlink/BOJ-Feature-Request#19]
틀린 데이터가 무엇인지 몰라서, 초보자인데도 별것도 아닌 문제에 시간을 허비하는 경우가 많습니다.
하지만 틀린 데이터를 무작정 다 보여주는 것은 디버깅 실력을 기르는 데 문제가 생길 것입니다.
이를 위해 다음과 같은 방법들을 제안합니다
1. 일정 시간 간격을 두고 틀린 데이터를 확인할 수 있도록 한다. 하루를 고민해도 안되면 틀린 데이터를 확인하고 고쳐야 한다고 생각합니다. 즉 하루에 한 번 자신이 틀린 데이터가 무엇인지 확인할 기회를 준다
2. 특정 횟수 이상(10회 이상이 적절해 보임) 제출하면 틀린 데이터 확인의 한 번의 기회를 준다.
3. 운영자가 쪽지를 받아 개인적으로 확인해 준다.

**Comment by Baekjoon** [comment]
틀린 데이터를 확인하는 기능은 현재로서는 만들 계획이 없습니다.
