### ISSUE TITLE
그룹 설명을 수정하면 새 그룹이 생성됩니다.

### ISSUE THREAD

**Issue by encrypted-def** [Startlink/BOJ-Feature-Request#190]
https://www.acmicpc.net/group/4490 이 그룹의 그룹 설명을 수정했더니 https://www.acmicpc.net/group/9780 이런 새로운 그룹이 생겼습니다.

한 두 달 전에도 비슷한 일을 겪었는데 인원수가 999명이 넘어가면 생기는 문제인가 싶기도 하고 원인을 정확하게는 모르겠네요.

**Comment by encrypted-def** [comment]
그룹 멤버들에게 혼동을 주는 것 같아 새로운 그룹은 제거했습니다.

**Comment by Baekjoon** [comment]
아니 이렇게 인원수가 많은 그룹이 있었다니

**Comment by Baekjoon** [comment]
확인해보겠습니다
