### ISSUE TITLE
공개 소스만 따로 보는 탭이 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by PororiLi** [Startlink/BOJ-Feature-Request#192]
공개 비공개 소스가 함께 섞여서 나와 공개 소스를 찾기가 힘듭니다. 보기 편하게 공개 소스만 따로 볼수 있는 탭을 만들어 주셨으면 좋겠습니다.

**Comment by Baekjoon** [comment]
안녕하세요.

말씀하신 기능이 생긴다면 "맞은 사람" 페이지나 "채점 현황"을 열심히 찾지 않고 편하게 공개된 소스만 볼 수 있어서 다른 사람의 소스를 읽어보는 것이 편할 것 같습니다.

현재의 BOJ 구조는 이를 지원하기가 매우 어렵습니다. 이를 지원하려면 여러가지 다양한 처리가 들어가야 할 것 같은데, 빠른 시일 내에 지원을 어려울 것 같습니다.

의견 남겨주셔서 감사합니다.
