### ISSUE TITLE
문제 질문 목록에서 해당 게시글의 언어를 보여주세요

### ISSUE THREAD

**Issue by hongsamchj** [Startlink/BOJ-Feature-Request#193]
대다수가 C++이라서 직접 눌러보며 언어를 확인해야 합니다...ㅠㅠ 파이썬, 자바 유저는 너무 슬퍼요

**Comment by Baekjoon** [comment]
안녕하세요.

업데이트 되었습니다.

좋은 의견 감사합니다.
