### ISSUE TITLE
출석 체크 기능이 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by yedamdamdam007** [Startlink/BOJ-Feature-Request#194]
레이팅이나 클래스처럼 다른 레벨?을 나타내는 기능을 하나 더 만들고 출석 체크 연속 날짜마다 레벨 점수를 올릴 수 있는 그런 출석체크 기능이 있으면 더 자주 접속하게 되지 않을까요?

**Comment by Baekjoon** [comment]
안녕하세요.

출석 체크는 현재 고려하고 있지 않습니다.

**Comment by yedamdamdam007** [comment]
감사합니다.
