### ISSUE TITLE
그룹에서 등급이 하나 더 추가되었으면 좋겠습니다.

### ISSUE THREAD

**Issue by yedamdamdam007** [Startlink/BOJ-Feature-Request#195]
현재는 그룹이 멤버와 관리자, 두 등급으로 나뉘고 있습니다.
그런데 여기에 관리자의 권한 일부만 가지고 있는 관리자와 멤버 사이의 등급이 추가되면 좋겠습니다.

**Comment by Baekjoon** [comment]
안녕하세요.

그룹은 상당히 오래 전에 만들어진 기능으로 사용성이나 기능적인 면에서 매우 많이 부족합니다. 아직도 메인 화면에 "무슨 내용을 넣어야 좋을까요?" 가 있기도 하지요.

그룹은 조금 더 사용하기 편하게 하기 위해서 업데이트를 준비하고 있습니다. 말씀하신 등급도 함께 계획되어 있습니다.

감사합니다.
