### ISSUE TITLE
웹사이트 및 블로그 정규표현식 수정 요청

### ISSUE THREAD

**Issue by wirekang** [Startlink/BOJ-Feature-Request#201]
마지막 레이블이 2~6글자로 제한되어 있는 바람에, 최상위 도메인이 6글자를 넘어가는 모든 URL은 웹사이트나 블로그로 인정받지 못합니다. 넉넉하게 조정 바랍니다.

* 이론상 최대 63
* 현존 최대 23

 제 도메인은 7글자라서 한 글자 차이로 등록이 안됩니다.

**Comment by Baekjoon** [comment]
수정했습니다.
