### ISSUE TITLE
맞은 사람 페이지의 아이디도 색칠해주세요. / 맞은 사람 소스코드를 언어에 따라 다중 조회할 수 있도록 해주세요.

### ISSUE THREAD

**Issue by Yoon-SeokJin** [Startlink/BOJ-Feature-Request#202]
1. 맞은 사람 페이지의 아이디도 색칠해주세요.
게시글 페이지에는 각 계정에 적용되어있는 코드포스/엣코더/탑코더 등급에 따라 작성자의 아이디 색상이 다릅니다. 그런데 맞은 사람 페이지의 아이디는 그렇지 않습니다. 다른 분들의 소스코드를 볼 때 저는 최대한 고수분들의 코드를 보려 하는데, 아이디의 색상이 다르다면 참고 지표가 될 수 있을 것 같습니다.

2. 맞은 사람 소스코드를 언어에 따라 다중 조회할 수 있도록 해주세요.
저는 C++을 사용합니다. 사실 C++11/C++14/C++17/C++20은 그리 중요하지 않습니다. 따로따로 찾아볼 필요 없이 C++계열의 제출된 모든 소스코드를 조회할 수 있었으면 좋겠습니다. (다른 분들께서 건의하신, 공개된 소스코드만 조회하는 기능도 있으면 시간을 아주 절약할 수 있겠네요!)

 감사합니다!

**Comment by Baekjoon** [comment]
1과 2 모두 오래 전부터 계획 중이며 올해 안에 만나볼 수 있을 것 같습니다.

**Comment by Baekjoon** [comment]
2에서 공개된 소스코드만 조회는 현재 계획은 있으나 언제 할지 모르는 상태입니다.

**Comment by Baekjoon** [comment]
안녕하세요.

현재는 2번은 사이트에 추가된 상태입니다. 맞힌 사람 페이지의 아이디 색상도 계획 중입니다.
