### ISSUE TITLE
내가 맞은 문제 중 언어별 등수가 1 또는 10 이하인 것들을 모아서 볼 수 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by yehwankim23** [Startlink/BOJ-Feature-Request#203]
![2021-08-11_22h49_00](https://user-images.githubusercontent.com/43813340/129040935-ac39ae8c-1553-40b0-8497-cabc85781c15.png)

**Comment by Baekjoon** [comment]
안녕하세요.

현재는 BOJ에서는 내 소스가 맞힌 사람 페이지에서 몇 등을 하고 있는지 알 방법이 없습니다.

추후에 개발하면서 이를 효율적으로 아는 방법이 생각나면 말씀하신 것을 한 번 구현해보겠습니다.
