### ISSUE TITLE
언어 랭킹에서 여러 버전의 언어를 하나로 묶은 카테고리가 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by yehwankim23** [Startlink/BOJ-Feature-Request#204]
![2021-08-11_22h53_44](https://user-images.githubusercontent.com/43813340/129041839-1217221c-bb1f-4a22-9dba-6080cc6edc1d.png)

**Comment by Baekjoon** [comment]
말씀하신 내용은 현재 계획 되어 있는 내용입니다.
