### ISSUE TITLE
문제마다 타이머기능이 있으면 어떨까요? ㅎㅎ

### ISSUE THREAD

**Issue by JiHooney** [Startlink/BOJ-Feature-Request#206]
약간 코테하는 느낌나도록 ㅎㅎ

오늘 갑자기 문제풀다가 집중이 잘 안되길래
1시간 설정해놓고 시간다되면 알람 울리는 타이머 기능 있으면
좋겠다는 생각을 해봤습니다 :)

**Comment by Baekjoon** [comment]
안녕하세요.

문제마다 타이머 기능은 좋은 기능인 것 같습니다. 업데이트 할 때 참고해서 지원해보겠습니다.

감사합니다.
