### ISSUE TITLE
문제 질문 남기기와 답글 API 제공

### ISSUE THREAD

**Issue by tjrkdgnl** [Startlink/BOJ-Feature-Request#207]
안녕하세요! 이번엔 알고리즘 관리 어플을 만들려고 합니다. 

### 기능요청
- 질문한 문제에 대한 API,  질문한 문제에 대한 답변 API

### 이유
-  백준 사이트를 이용하면서 제가 질문한 문제들을 모아두는 별도의 공간이 없어서 시간이 지나면 무엇을 질문했는지,
답변은 달렸는지 알기 어려웠습니다. 이러한 부분을 앱을 만들면서 좀 더 개선하고자 합니다. 

solved.ac api만으로는 해당 기능을 구현하기 어려워서 이렇게 글 남깁니다.  

### ps
- 문제 검색 API를 통해 얻는 Response에는 지문과 테스트 케이스는 얻을 수 없던데 이는 저작권 관련 문제가 있을까요?

**Comment by Baekjoon** [comment]
안녕하세요.

현재 API 제공 계획은 있으나 정확한 시기나 방법은 정해지지 않고, 언젠가 제공 하겠다는 생각만 있는 상태입니다.
