### ISSUE TITLE
Go 언어 버전 업그레이드 부탁드립니다.

### ISSUE THREAD

**Issue by geeksbaek** [Startlink/BOJ-Feature-Request#21]
현재 Go 1 버전이 적용되어 있는 것으로 알고있습니다.

많은 버전업을 거쳐 현재 1.6.2버전까지 출시되었는데, 많은 새 기능들이 추가된 만큼 업그레이드 할 필요가 있다고 생각합니다.

**Comment by Baekjoon** [comment]
업그레이드 했습니다.
