### ISSUE TITLE
재채점시 결과가 바뀐 경우만 알림이 오도록 설정하고 싶어요

### ISSUE THREAD

**Issue by sh-cho** [Startlink/BOJ-Feature-Request#210]
맞았습니다 -> 틀렸습니다 로 된 재채점만 알림이 왔으면 좋겠어요

**Comment by Baekjoon** [comment]
안녕하세요.

알림 기능이 상당히 오래 전에 만들어져서, 현재 알림 시스템을 다시 구현하고 있습니다.

재채점이 많은 요즘, 말씀하신 기능은 상당히 유용할 것 같습니다.

알림 기능을 구현할 때 참고하겠습니다.

감사합니다.
