### ISSUE TITLE
Elixir 언어에 대한 지원을 요청드립니다.

### ISSUE THREAD

**Issue by ByeongUkChoi** [Startlink/BOJ-Feature-Request#211]
함수형 프로그래밍에 대한 관심이 증가함에 따라 함수형 언어인 elixir에 대한 지원을 요청드립니다.

https://github.com/elixir-lang/elixir

**Comment by Baekjoon** [comment]
안녕하세요.

꽤 오래 전부터 Elixir를 추가하려고 노력했으나, 채점 프로그램과 호환이 되지 않아 추가가 되지 않고 있습니다.

다음 채점 프로그램 업데이트에 한 번 시도해보겠습니다.

감사합니다.

**Comment by ByeongUkChoi** [comment]
엘릭서가 추가되어서 많은 사람이 함수형 언어로 재미있게 알고리즘 문제를 풀수 있길 기대해 봅니다. 감사합니다.
