### ISSUE TITLE
게시판-질문에서 특정 언어만 선택적으로 열람할 수 있는 기능이 추가되었으면 합니다.

### ISSUE THREAD

**Issue by Dizlet** [Startlink/BOJ-Feature-Request#213]
문제 검색처럼 직접 and, or연산으로 보는것도 괜찮을 것 같고,
버전이 많은 언어라면, 언어별 랭킹처럼 몇몇 언어들을 그룹화해서 질문을 볼 수 있으면
질문에 답변을 달기가 훨씬 수월할 것 같습니다.

더불어, '미해결 질문'만 볼 수 있게 하거나, '댓글이 달리지 않은' 질문만 본다거나.. 이런 기능도 추가되면 좋을것 같습니다.

(댓글 0개)&(미해결상태)&(c++그룹)의 질문만 보기.. 이런게 가능해졌으면 합니다.

**Comment by Baekjoon** [comment]
안녕하세요.

게시판은 현재 업데이트 중으로 말씀하신 의견도 함께 고려해서 업데이트 진행해보겠습니다.
