### ISSUE TITLE
질문 게시판 글들이 좋아요 수가 높은 순으로 게시되는 기능이 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by keunbum** [Startlink/BOJ-Feature-Request#214]
예를 들어 [수 정렬하기 2](https://www.acmicpc.net/problem/2751) 문제의 경우,
[이 게시글](https://www.acmicpc.net/board/view/31887)이 먼저 눈에 띄었다면 질문 수가 더 적었을 거라 예상됩니다.

https://help.acmicpc.net/question 이런 링크글들을 제대로 다 읽어보고 boj를 이용하시는 분들은 많지 않을 거라 생각됩니다.

**Comment by Baekjoon** [comment]
안녕하세요.

게시판의 여러가지 불편한 점과 계속해서 올라오는 중복 질문 등을 줄여보기 위해 게시판을 다시 구현해보고 있습니다. 추천 순 정렬의 경우 좋은 아이디어라 생각되어 새로 구현해본 게시판에는 이를 추가했습니다.

좋은 의견 주셔서 감사합니다.
