### ISSUE TITLE
컴파일러 선택 기능

### ISSUE THREAD

**Issue by Powering111** [Startlink/BOJ-Feature-Request#218]
C++ 같은 경우에도 GCC나 Visual C++ 등으로 컴파일러가 여러 가지가 있는데, 서로 기능이 조금씩 차이가 있습니다. 쉽지 않겠지만 이러한 언어들을 제출할 때 컴파일러를 선택할 수 있으면 좋을 것 같습니다.

**Comment by Baekjoon** [comment]
C++은 gcc와 clang 두가지 컴파일러를 지원하고 있습니다. 

말쓴하신 Visual C++로는 리눅스에서 컴파일 할 방법이 없습니다.
