### ISSUE TITLE
자신이 제출한 코드의 채점을 중단할 수 있는 기능

### ISSUE THREAD

**Issue by xnuk** [Startlink/BOJ-Feature-Request#219]
가끔씩, 코드를 제출한 후에야 버그를 찾거나, 코드 복붙을 잘못 했다거나, 언어 선택을 잘못 했다거나, 등의 여러 가지 이유로 제출 후에 "이 코드는 통과하지 못할 것이다"를 확신하는 경우가 있습니다. 이런 코드가 `기다리는 중` 또는 `채점 준비 중` 상태에 들어가면 수정해서 제출한 새 코드는 그만큼 채점이 늦어질 수 있고 그럴 때마다 채점 서버 리소스가 아깝...다는 생각이 항상 듭니다 서버 관리자 입장에서는 몇십 원 차이도 안 될지 모르겠지만요

그래서 제출한 코드를 채점을 중단시키거나, 혹은 아예 삭제할 수 있는 기능(이쪽이 더 구현 삯이 덜 든다면)이 있으면 좋을 듯합니다.

**Comment by Baekjoon** [comment]
채점 중단을 구현하는 것이 현재는 어려울 것 같습니다.
