### ISSUE TITLE
문제 별 오르는 점수 표시

### ISSUE THREAD

**Issue by sanghyeonjung** [Startlink/BOJ-Feature-Request#221]
솔브닥의 점수계산은 상위 100문제의 점수를 기준으로 되기 때문에 이 문제를 풀면 몇점이 오르는지 점수를 계산해주는 기능을 넣으면 좋을 것 같습니다. 인터넷 상에도 오르는 점수를 계산해주는 프로그램이 아직 존재하지 않아서 꽤 유용한 기능일 것 같습니다

**Comment by Baekjoon** [comment]
이 부분은 BOJ의 역할이 아닙니다. solved.ac나 다른 확장 프로그램의 역할로 보입니다.
