### ISSUE TITLE
소스코드 금지어 기능을 건의합니다.

### ISSUE THREAD

**Issue by pnkprst** [Startlink/BOJ-Feature-Request#222]
주어진 값들중에서 최대값을 내놓아야 하는 문제에서는 max 함수를 쓰고
이진수로 변환한 값을 내놓아야 하는 문제에서는 bin 함수를 쓰고
팩토리얼 값을 내놓아야 하는 문제에서는 math 모듈을 불러온 뒤 factorial 함수를 쓰는 등
문제를 내장 라이브러리로 날로 먹는 상황이 흔하게 발생합니다.
어떻게 작동하는지 알고 쓴다면 좋겠지만 실상은 사용방법만 아는 추세입니다.
이는 제출자의 알고리즘 설계능력을 키우지 못하게 합니다.
또한, 내장 라이브러리가 빈약한 언어는 활용이 빈약하게 됩니다.

따라서, 모든 제출자가 직접 알고리즘을 설계하게 만들기 위해 
문제에서 금지어를 설정할 수 있게하고,
소스코드에 금지어가 포함되어있다면 오답으로 처리되면 좋겠습니다.

**Comment by shiftpsh** [comment]
C 전처리기 사용이나 Python `eval` 등 완벽하게 막을 수 있는 방법은 없는 것으로 아는데 좋은 방법인지는 잘 모르겠습니다.

**Comment by Baekjoon** [comment]
완벽하게 막을 수 있는 방법이 없어 지원할 수가 없습니다.

**Comment by parkyere** [comment]
소프트웨어 공학에서 흔히 하는 이야기가 있습니다: "바퀴를 재발명하지 말라".
물론 알고리즘이 이미 언어 기본 라이브러리로 구현되어 있다 해도,
스스로 짜 보는 건 좋은 공부가 될 수 있긴 합니다.
그런데 현업에서는 정말 해서는 안되는 일입니다.
라이브러리 사용을 익숙하게 하는 것도 현업에서는 요구되는 능력 중 하나입니다.
그런데 그 이유 하나만으로 기본 라이브러리를 막자는 발상은 매우 위험해 보입니다.
