### ISSUE TITLE
프로필에 댓글이 달렸을 때 알림 기능

### ISSUE THREAD

**Issue by xdoju** [Startlink/BOJ-Feature-Request#23]
제 프로필 페이지에 어떤 분이 댓글로 질문을 하셨는데, 딱히 알림이 온 것도 아니고 제가 제 프로필을 볼 일도 없다 보니 한 달이 넘게 지나서야 확인했습니다..
소스에 댓글이 달렸을 때는 알림이 오는 것 같던데 프로필의 경우도 알림이 왔으면 좋겠습니다.

**Comment by Baekjoon** [comment]
프로필 댓글은 삭제되었습니다.
