### ISSUE TITLE
solved.ac 스트릭 프리즈 최대 개수 증가를 요청합니다.

### ISSUE THREAD

**Issue by hu5768** [Startlink/BOJ-Feature-Request#235]
2월 초 쯤에 혹한기 훈련을 가는 군인들을 위해서
스트릭 프리즈의 최대 개수를 5개 정도로 늘리는 기능을 제안합니다.

**Comment by shiftpsh** [comment]
안녕하세요, solved.ac 기능 관련 문의는 이 레포의 포커스가 아닙니다. solved.ac 관련 문의사항이 있으시다면 shift@solved.ac로 부탁드리겠습니다.

말씀해주신 기능은 유감스럽게도 현재로서는 수정하기 약간 힘든 상황입니다. 아마 2월 초에 반영하기는 힘들 것으로 예상합니다.
