### ISSUE TITLE
대회 스코어보드에서 각 사용자마다 대회 중 submission 기록을 모아볼 수 있는 페이지

### ISSUE THREAD

**Issue by ntopia** [Startlink/BOJ-Feature-Request#24]
스코어보드에서 ntopia 기록보기 를 누르면

00:11 J AC 
00:30 I AC 
00:39 K RE 
00:41 K RE 
00:44 K AC 
00:52 E AC 
01:12 C AC 
01:17 A WA 
01:21 A AC 
01:51 G WA 
02:50 G AC 
02:52 H WA 
03:12 H WA 
03:15 H WA 
03:16 H CE 
03:16 H WA 
03:24 H WA 
03:34 H WA 
03:38 H WA 
03:45 H AC 

Solved : 8, panelty : 925 

이와 같이 submission history를 시간에 따라 볼 수 있는 기능이 있으면 좋겠어요.

BOJ 공식대회, 그룹대회 기능 둘 다요

**Comment by Baekjoon** [comment]
일단 BOJ 보드는 이를 지원하고 있습니다.

스팟보드는 뭔가 어려워 보입니다.
