### ISSUE TITLE
C++20 컴파일 시 gcc/g++ 12 버전 이상을 사용해 주세요.

### ISSUE THREAD

**Issue by MinetaS** [Startlink/BOJ-Feature-Request#244]
C++20 가 지원하는 `constexpr std::string` 이나 `constexpr std::vector` 는 gcc 12 이상 버전부터 지원합니다.

![image](https://github.com/Startlink/BOJ-Feature-Request/assets/31549467/3fe69d55-3289-4729-a169-7fdbef00861e)

코어가 아니라 라이브러리 표준이긴 하지만 string과 vector 모두 광범위하게 사용된다는 점을 고려해서 이슈 오픈합니다.
13 버전은 현재로써는 experimental 버전이 배포되는 만큼 12.2 를 사용하면 좋을 것 같습니다.

https://www.acmicpc.net/ceinfo/64232221

위 코드는 constexpr 멤버 함수를 사용해서 컴파일 에러가 발생했습니다.

**Comment by Baekjoon** [comment]
현재 BOJ의 채점 서버에서는 gcc 12의 컴파일이 되지 않아 지원할 수 없습니다. 채점 서버에 큰 변화가 있은 이후에 지원할 예정입니다.
