### ISSUE TITLE
사이트 공지사항..

### ISSUE THREAD

**Issue by SeokminHong** [Startlink/BOJ-Feature-Request#26]
규정/공지사항 확립해서 올려주시면 좋겠습니다.
아직까지는 큰 문제는 없었지만 명시된 규정이 없으니 불안해 보입니다.
일단 가장 필요해 보이는 건, 게시판 이용규정, 문제 제출시(공개 코드에 불건전한 주석을 넣거나 옛날 어떤 분이 wait 함수로 트롤링 하는 것을 막기 위함), 변역 규정(부실한 번역 규제, 번역시 인물/스토리 등 각색 허용 정도 등) 정도가 있겠네요.
불량 이용자 신고 기능도 있으면 좋겠습니다.

**Comment by Baekjoon** [comment]
추가할 예정입니다.

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
