### ISSUE TITLE
가입 신청 알림 링크 오류

### ISSUE THREAD

**Issue by mintrupt** [Startlink/BOJ-Feature-Request#27]
그룹 관리자일 때, 새로운 그룹 가입 신청이 들어왔을 때 https://acmicpc.net/notifications 에 나오는 "~팀에 가입 신청을 했습니다." 알림에 있는 링크가 https://acmicpc.net/team/member/{번호} 로 걸려 있어 404를 얻습니다.

**Comment by Baekjoon** [comment]
수정했습니다.
