### ISSUE TITLE
Rust 언어 추가해주세요

### ISSUE THREAD

**Issue by alkorang** [Startlink/BOJ-Feature-Request#29]
Version 1.0.0 이 2015-05-15에 release 되었고,
현재 기준으로 2016-05-26에 나온 1.9.0 버전이 최신입니다.
Mozilla에서 제작중인 Servo 엔진에 사용되는 언어입니다.
추가될 가치가 충분히 있다고 생각됩니다.

**Comment by Baekjoon** [comment]
1.10.0이 추가되어 있습니다.
