### ISSUE TITLE
질문 게시판의 해결 기능 강화?

### ISSUE THREAD

**Issue by CodeSang** [Startlink/BOJ-Feature-Request#30]
댓글이 안달리고 해결이 되지 않은 게시글을 우선적으로 볼 수 있으면 어떨까요..

답글이 안달리고 묻히는 질문글들이 안타까워서 말씀드려 봅니다.

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
