### ISSUE TITLE
대회 중 해결한 문제들의 채점현황 내 편의성 개선

### ISSUE THREAD

**Issue by xdoju** [Startlink/BOJ-Feature-Request#31]
유저가 대회 중에 문제를 해결할 경우 채점 현황에 문제 ID 대신 대회에서 부여받은 알파벳으로 표시가 되고 있습니다. (ex. https://www.acmicpc.net/status/?user_id=doju&top=3207558 )
그런데 이 경우 맞은 문제가 굵게 표시되는 기능도 작동하지 않고, 알파벳으로 표기되어도 그게 어떤 대회였는지도 알 수 없기 때문에 편의성이 굉장히 나쁩니다.

이 기능은 대회 페이지에서 해당 대회의 채점 현황을 확인할 때에만 필요해 보이는데, 채점 현황을 contest id로 접근할 때에만 알파벳으로 보여 주고 그 외의 경우는 다른 문제들처럼 문제 ID로 표시되고 highlight 기능 역시 작동되었으면 좋겠습니다.

**Comment by Baekjoon** [comment]
저랑 같은 생각을 하고 계시네요

**Comment by Baekjoon** [comment]
개선했습니다.

**Comment by xdoju** [comment]
여전히 그대로입니다. https://www.acmicpc.net/status/?user_id=doju&top=4151132

**Comment by Baekjoon** [comment]
수정했어요
