### ISSUE TITLE
topcoder 계정 연동

### ISSUE THREAD

**Issue by Myeongjoon** [Startlink/BOJ-Feature-Request#33]
대단한 issue는 아니나 현재 탑코더 계정 연동 방식은 밑의 그림처럼 되어있습니다.

![123](https://cloud.githubusercontent.com/assets/17864835/17051426/a71876c2-5033-11e6-9616-27a69fe35f37.png)

그러나 탑코더에 들어가면 UI 도 많이 바뀌었고 오른쪽 상단 클릭하면 숫자 id가 나오지 않습니다.

URL 형식이 https://www.topcoder.com/members/kimmj8409/ 이렇게 나옵니다.

![456](https://cloud.githubusercontent.com/assets/17864835/17051551/4a7212f6-5034-11e6-98d4-5a027ad86458.png)

이 위치에서 `FORUM POST`를 누르니 

https://apps.topcoder.com/forums/?module=History&userID=40456958 이런 URL이 나오긴 합니다.

사소한 issue이지만 바꾸면 좋긴 할듯합니다.

**Comment by kbu1564** [comment]
http://docs.tcapi.apiary.io/#reference/user-profile/my-profile/my-profile
TopCoder 관련 API 가 있기에 올려봅니다!

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
