### ISSUE TITLE
그룹, 문제집, 연습도 즐겨찾기 가능하게 해주세요.

### ISSUE THREAD

**Issue by ashgold** [Startlink/BOJ-Feature-Request#34]
같이 스터디하는 사람들끼리 그룹을 만들고,
그 그룹 안에서 문제집이랑 연습을 등록한 후에 같이 풀어보는 편인데요.
항상 사이트 들어올 때마다 경로를 타고 들어가야 돼서 매우 불편해요..

그룹 안에 있는 문제집, 연습을 즐겨찾기 할 수 있게 해주세요.
감사합니다.

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
