### ISSUE TITLE
사용자 페이지 부분 푼 문제, 틀린 문제의 분류증가

### ISSUE THREAD

**Issue by kbu1564** [Startlink/BOJ-Feature-Request#35]
사용자 페이지에서 맞춘 문제를 좀더 분류화 하여 보기위해 영문문제, 혼자 푼 문제들만 별도로 보여주는 부분이 있으면 좋을 것 같습니다.

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
