### ISSUE TITLE
스코어보드에서 코드 바로가기

### ISSUE THREAD

**Issue by elbaro** [Startlink/BOJ-Feature-Request#36]
스코어보드의 초록 칸/빨간 칸 클릭시 제출코드로 바로 이동 (혹은 2개 이상일시 제출목록)

ex)
- 대회가 끝난 후 다른 팀이 어떻게 풀었나 바로 확인가능
- 그룹/연습에서 강사가 학생들의 코드를 바로 확인/피드백 가능

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
