### ISSUE TITLE
연습 세션에서 공지 기능

### ISSUE THREAD

**Issue by elbaro** [Startlink/BOJ-Feature-Request#37]
연습 세션에서 공지 기능

연습 세션에서는 문제의 설명이나 데이터가 바뀔 일은 없지만, 다음과 같이 교육용으로 활용이 가능합니다.
"H번은 매우 어려우니 나중에 푸세요"
"J번은 부동소수점 오차에 유의하세요"
"D번의 2-SAT 설명 잘 된 자료: http:// ... "

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
