### ISSUE TITLE
그룹 메인페이지 그룹 관리자가 변경 가능하도록

### ISSUE THREAD

**Issue by kbu1564** [Startlink/BOJ-Feature-Request#38]
그룹 메인페이지에 해당 그룹을 대표하는 특색있는 글이나 사진을 넣고 싶은데.
수정할 수 있도록 해주시면 좋을 것 같습니다.!

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
