### ISSUE TITLE
코드 댓글 알림이 작동하지 않음

### ISSUE THREAD

**Issue by elbaro** [Startlink/BOJ-Feature-Request#40]
현재 모임에서 다른 분들의 코드를 보고 댓글을 달아드리고 있는데
코드 열람 알람은 뜨지만 댓글 알람이 뜨지 않는다고 하시는 분이 많습니다

**Comment by Baekjoon** [comment]
disqus를 삭제했습니다.

곧 다시 댓글 다는 기능이 열릴 예정입니다.
