### ISSUE TITLE
내가 푼 문제만 한정해서 검색하는 기능이 있었으면 좋겠어요

### ISSUE THREAD

**Issue by sency90** [Startlink/BOJ-Feature-Request#42]
이전에 뭔가 풀었던 문제가 떠올랐는데,
그걸 푼 문제에서만 검색해보면 빠를 것 같은데 본인 계정 상태보면 그냥 푼 문제 번호만 나와서요.
(문제 번호가 기억나지도 않고.. 전체 검색해보니 너무 많이 뜨고...)

풀었던 문제만 한정지어서 검색하는 기능이 있었으면 좋겠습니다~~!
그리고 여력이 되신다면, 알고스팟처럼 풀었던 문제 분류기능도 있었으면 좋겠습니다.ㅎ

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
