### ISSUE TITLE
문제집 정렬기능 있었으면 좋겠어요!

### ISSUE THREAD

**Issue by hanmar88** [Startlink/BOJ-Feature-Request#44]
문제집을 list로 확인했을 때,

clear한 사람 수로 정렬해서 가장 많이 푼 문제집부터 확인하고 싶어요!

그 기능이 추가됐음 좋겠어요

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
