### ISSUE TITLE
Codeground에서 보고 좋았다 싶은 점인데..

### ISSUE THREAD

**Issue by hanmar88** [Startlink/BOJ-Feature-Request#45]
문제에서 맞은 사람을 볼 때 공개된 코드들이 있는데,
여기에 좋아요! 를 눌러서 좋아요 수로 정렬되는 기능이 있으면 좋을 거 같아요..

그러면.. 괜찮은 코드를 더 빠르게 찾을 수 있을 거 같은데..

싸이트에 문제나 맞은 사람의 수가 워낙 많아서,
좋아요 수가 정렬되기 까지 시간이 걸릴 수도 있겠어요..

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
