### ISSUE TITLE
Golang으로 제출한 답안 중 일부가 채점이 제대로 안 되고 있습니다.

### ISSUE THREAD

**Issue by BupjaeLee** [Startlink/BOJ-Feature-Request#49]
![golang_err](https://cloud.githubusercontent.com/assets/1683826/19613590/474f89d2-9828-11e6-8af7-24dd8ab40a84.png)

"채점중" 상태에서 더 이상 진행이 되지 않고 있습니다.

**Comment by Baekjoon** [comment]
수정완료
