### ISSUE TITLE
프로필 페이지 개선

### ISSUE THREAD

**Issue by handrake** [Startlink/BOJ-Feature-Request#55]
개인 프로필 화면에 들어가면 푼 문제가 모두 나오는데 상위 랭커의 경우 목록이 길어서 로딩이 상당히 느려집니다. (어쩔 땐 10초 이상 소요)

일정 숫자가 넘어가면 다중페이지로 만들 거나 하면 로딩 속도가 높아질 것 같습니다.

**Comment by Baekjoon** [comment]
혹시 제가 테스트해볼 수 있게 사용하는 환경을 알려주시겠나요?

제가 쓰는 기계에선 전부 렌더링하는데 시간이 얼마 안들어서요.

**Comment by handrake** [comment]
Windows 10 Home

CPU: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz 3.40Ghz
RAM: 16GB

Chrome
54.0.2840.71m (64-bit)

이런 구성입니다.

Internet Explorer
11.321.14393.0

에서 확인한 결과 시간은 줄어들지만 1초가량 멈칫합니다

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
