### ISSUE TITLE
64bit 채점서버

### ISSUE THREAD

**Issue by ntopia** [Startlink/BOJ-Feature-Request#58]
채점환경을 64bit 으로 업그레이드하면 좋겠습니다.

현재 boj 채점서버는 32bit라서 long long 을 쓰면 심각하게 느려지는 문제가 있습니다.

몇년전부터 열리는 대회들은 거의 다 64bit 채점서버를 기준으로 문제와 데이터가 만들어지고 있습니다. 이 문제들을 boj에서 풀 때 애로사항이 꽃피는 일이 종종 있습니다.

그리고 온라인 저지를 오래오래 운영하려면 낡은 레거시를 적절히 버릴 필요도 있다고 생각합니다. 현재 적지않은 소프트웨어들이 32bit OS 지원을 포기하고 있습니다. 앞으로는 더 많아지겠죠...

**Comment by Baekjoon** [comment]
64비트로 성공적으로 이전했습니다.
