### ISSUE TITLE
스코어보드가 페널티 대신 푼 시각을 표시해 줬으면 좋겠습니다.

### ISSUE THREAD

**Issue by xdoju** [Startlink/BOJ-Feature-Request#62]
문제별 페널티보다는 문제를 푼 시각이 더 중요한 정보라고 생각합니다. 문제를 푼 시각을 확인하는 것은 각 팀의 페이스나 각 문제의 대략적인 풀이 시간을 가늠하는 데 유용하게 쓰일 수 있습니다. 또한 First solve로 색칠되어 있는 서브밋이나 더 일찍 풀었던 문제의 서브밋이 다른 서브밋보다 더 큰 숫자가 적혀 있을 경우 위화감을 줍니다(이는 단순히 다른 대부분의 스코어보드들이 푼 시각을 보여 주기 때문일지도 모릅니다).
그리고 BOJ 내의 table 기반 스코어보드에도 First solve에 대해 다른 색을 칠해 주면 보기 좋을 것 같습니다.

**Comment by Baekjoon** [comment]
그건 BOJ의 수많은 스코어보드 타입 중에 하나일 뿐입니다.

https://www.acmicpc.net/contest/scoreboard/84

이런 스코어 보드 타입도 있는데, 제가 기본 세팅으로 대회를 열고, 그걸 그룹 연습내에도 반영을 하지 않아서 그렇습니다.

그룹 스코어보드를 말씀하시는거면 그룹 스코어보드 타입도 여러가지를 선택할 수 있게 만들어놓겠습니다.

퍼스트 솔브에 색칠하는건 좋은 생각입니다.

**Comment by Baekjoon** [comment]
현재 시점엔 지원하고 있습니다.
