### ISSUE TITLE
부분 점수 문제 만점일 때만 다른 사람 소스 열람 가능하게 해주세요

### ISSUE THREAD

**Issue by Baekjoon** [Startlink/BOJ-Feature-Request#66]
부분 점수 문제 만점일 때만 다른 사람 소스 열람 가능하게 해주세요

https://www.acmicpc.net/problem/3090

**Comment by Baekjoon** [comment]
이 기능을 구현하고 https://www.acmicpc.net/board/view/9623 를 재채점 해주세요

**Comment by BupjaeLee** [comment]
이 정책을 적용할 때 문제별로 유연하게 적용했으면 합니다.

3090번 문제 같은 경우 100점만 소스 열람이 맞지만
8873번 문제 같은 ML 문제를 정확도 100% 라는 건 사실상 불가능하므로 70~80% 정도 받으면 소스를 볼 수 있게 하고
11921번 문제 같은 경우 알고리즘 문제라기 보다는 입출력 빙법론 이기 때문에 현재 정책을 유지하는게 좀 더 좋은 선택이지 않을까 생각하고 있습니다.

**Comment by Baekjoon** [comment]
구현되어있습니다.
