### ISSUE TITLE
질문 게시판에서 해결 과 해결안됨 버튼 

### ISSUE THREAD

**Issue by nhs0912** [Startlink/BOJ-Feature-Request#69]
해결과 해결 버튼 버튼이 있잖아요..텍스트로 된...버튼!

근데 이걸 누르면 해결안됨으로 표시가 되고 해결안됨을 누르면 해결로 표시가 되니깐..

해결로 하려면 내가 보기엔 해결안됨으로 표시 되는것이 해결로 된건지 그 반대인지...무지 헷갈리네요..

뭔가 컬러풀하게 구분이 되었음 좋겠습니다. 직관적으로요~

**Comment by Baekjoon** [comment]
저도 그게 너무나도 헷갈려요 ㅠㅠ

**Comment by nhs0912** [comment]
헉....저만 헷갈린게 아니였군요..ㅋㅋㅋ

**Comment by Baekjoon** [comment]
업데이트 되었습니다.
