### ISSUE TITLE
연습이나 문제집에 여러 문제를 한 번에 추가할 수 있게 해 주세요.

### ISSUE THREAD

**Issue by xdoju** [Startlink/BOJ-Feature-Request#73]
여러 문제를 한꺼번에 추가하려고 할 때, 한 문제씩 번호 입력하고 엔터 눌러서 추가하는 것은 번거롭기도 하고 실수도 많이 하게 됩니다. 특정 구분자(공백, 콤마 등)를 사이에 두고 여러 개의 문제 번호를 입력하면 한 번에 추가되는 기능이 있으면 좋겠습니다.

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
