### ISSUE TITLE
문제에서 맞은 사람 소스볼 때 언어선택하는 기능 문의 

### ISSUE THREAD

**Issue by nhs0912** [Startlink/BOJ-Feature-Request#77]
문제에서 맞은 사람 소스볼 때 언어선택하는 기능 문의 

언어를 선택해서 맞은 사람중에 자신에게 맞는 언어만 보고 싶은데 그런 기능이 없네요..ㅠ

이 기능 있으면 편리할거 같아요!

**Comment by Baekjoon** [comment]
좋네요 바로 추가할게요

**Comment by nhs0912** [comment]
감사합니다 바로 추가 되어서 좋네요!! 잘 이용할게요^^

**Comment by Baekjoon** [comment]
추가되었습니다
