### ISSUE TITLE
PHP 채점이 이상합니다

### ISSUE THREAD

**Issue by veydpz** [Startlink/BOJ-Feature-Request#82]
안녕하세요. PHP로 1000(A+B) 문제를 풀어보려 했는데요
- [언어 가이드](https://www.acmicpc.net/help/language)에 나와있는대로 제출해도 틀리고
- 4주 전에 맞은 사람의 코드와 동일한 코드를 제출해도 틀리고 있습니다.

지난 1달간 아무도 PHP로 제출해서 맞은 사람이 없는 것으로 보아, 채점이 정상적으로 이루어지지 않고 있는 것 같습니다. 확인 부탁드립니다.

**Comment by Baekjoon** [comment]
PHP를 잠시 삭제했습니다.

**Comment by veydpz** [comment]
1000번 문제를 기준으로, 이제는 다시 정상 작동함을 확인하였습니다. 이슈를 닫겠습니다.
고쳐 주셔서 감사합니다.
