### ISSUE TITLE
python submit tool

### ISSUE THREAD

**Issue by sency90** [Startlink/BOJ-Feature-Request#83]
다시 작동되게 만들어주세요. ㅠㅠ

boj 처음 이용할때부터 쓰다가 갑자기 안되니까 너무 불편해요 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅜㅜㅜㅜㅜㅜㅜㅜㅜ

갤럭시 쓰는데 삼성페이 못쓰는 느낌.

**Comment by sency90** [comment]
https://github.com/Baekjoon/submit-tool

수정이 절실하다.

**Comment by sency90** [comment]
백준님이 고쳐줬으면 참 좋겠다.

**Comment by Baekjoon** [comment]
앞으로 제공하지 않기로 결정되었습니다.
