### ISSUE TITLE
게시판 "작성자" 검색시 "답변 작성자" 검색 추가 건의

### ISSUE THREAD

**Issue by BupjaeLee** [Startlink/BOJ-Feature-Request#84]
지금은 스레드 첫 번째 작성자가 주어진 id일 때만 검색이 가능한데

스레드에 달린 답변의 작성자 id로도 검색이 가능한 옵션이 있으면 좋을 것 같습니다.

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
