### ISSUE TITLE
오탈자 발견관련...

### ISSUE THREAD

**Issue by BlazingCode** [Startlink/BOJ-Feature-Request#85]
https://www.acmicpc.net/help/judge
중 "왜 컴파일에러가 나는지 모르겠어요 "의
첫번째 <li>태그안의 "g++"이 아니라 "c++" 아닌가요??

**Comment by Baekjoon** [comment]
g++이 맞습니다.

**Comment by Baekjoon** [comment]
아니 gcc가 맞겠네요.
