### ISSUE TITLE
게시판 댓글 수정 기능

### ISSUE THREAD

**Issue by xdoju** [Startlink/BOJ-Feature-Request#87]
댓글(특히 질문에 대한 답변)을 작성한 뒤 사소한 수정을 하고 싶어지는 경우가 자주 있는데 수정 기능이 없어 불편합니다. 지금은 아예 삭제한 다음 글을 다시 작성하고 있는데 굉장히 번거롭고 질문자에게 알림도 여러 번 갈 것 같아 괜히 미안해집니다.
댓글도 게시글과 같이 작성자가 수정할 수 있는 기능을 지원했으면 좋겠습니다.

**Comment by xdoju** [comment]
10번 이슈와 중복이네요. https://github.com/Startlink/BOJ-Feature-Request/issues/10
미리보기 기능도 적극 요청합니다. 에디터에서 보이는 줄바꿈과 실제로 글을 등록했을 때 적용되는 줄바꿈이 달라서 보기 싫어지는 경우가 많아요.

**Comment by Baekjoon** [comment]
대체 왜 처음 만들때 수정을 안만들었을까요?

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
