### ISSUE TITLE
"메모리 초과"를 판단하는 기준의 개선이 필요합니다.

### ISSUE THREAD

**Issue by BupjaeLee** [Startlink/BOJ-Feature-Request#89]
https://www.acmicpc.net/board/view/11461
https://www.acmicpc.net/board/view/11572

위 두 답안은 문제에서 제한한 것 보다 더 많은 메모리를 사용하기 했기 때문에 실패한 답안입니다만, "메모리 초과" 메세지 대신 "런타임 에러" 메세지를 받았습니다.

**Comment by Baekjoon** [comment]
채점 번호: 5265970

**Comment by Baekjoon** [comment]
채점 번호: 5265970 는 수정됨
