### ISSUE TITLE
맞는 코드가 틀렸다고 채점되는 경우가 있습니다.

### ISSUE THREAD

**Issue by xdoju** [Startlink/BOJ-Feature-Request#90]
https://www.acmicpc.net/board/view/11501
https://www.acmicpc.net/board/view/11783
> acka [1:56 PM] added this C++ snippet: 11047_동전0
acka [1:57 PM] 가끔 메모리 관련해서 원래 런타임에러나 그런류로 틀려야하는 코드가 맞게될때는 있었는데
acka [1:57 PM] 저걸 C++14로 제출했는데 한번은 틀리고 한번은 맞습니다

채점이 올바르게 되는 것은 온라인 저지의 의무입니다. 당장 오류를 겪은 사람들은 있지도 않은 버그를 잡는 데에 오랜 시간을 낭비하다가 결국 데이터를 의심하게 되고, 오류를 겪지 않았더라도 혹시 발생했을지도 모르는 오류 때문에 틀린 코드를 두세번씩 제출해 볼 수도 없는 노릇입니다.
아주 중요한 문제라고 생각하는데 빠른 해결 부탁드립니다.

**Comment by Baekjoon** [comment]
수정했습니다.
