### ISSUE TITLE
Solarized dark theme

### ISSUE THREAD

**Issue by ikasty** [Startlink/BOJ-Feature-Request#94]
별 거 아니지만, Solarized Dark theme을 추가해 주시면 감사하겠습니다.

[solarized theme 페이지](http://ethanschoonover.com/solarized)

기존에 등록되어 있던 Solarized theme에서 색상 팔레트 네 개만 변경하면 될 것 같습니다.

**Comment by Baekjoon** [comment]
CodeMirror에서 현재 지원하지 않아 현재는 불가능합니다.

**Comment by Baekjoon** [comment]
수정되었습니다.
