### ISSUE TITLE
자동완성되는 문제 제목이 실제 문제 제목과 다릅니다.

### ISSUE THREAD

**Issue by xdoju** [Startlink/BOJ-Feature-Request#95]
<img width="673" alt="2017-01-26 2 53 21" src="https://cloud.githubusercontent.com/assets/4413599/22321353/45e4df5c-e3d7-11e6-9552-a191b363edff.png">
<img width="581" alt="2017-01-26 2 53 34" src="https://cloud.githubusercontent.com/assets/4413599/22321354/4b7b2eb2-e3d7-11e6-933c-ff90500c14b5.png">

**Comment by Baekjoon** [comment]
자동완성을 빼버리겠습니다.

**Comment by Baekjoon** [comment]
수정했습니다.

캐시 때문에 쵣 ㅐ48시간이 걸립니다.
