### ISSUE TITLE
연간 랭킹 1위 관련

### ISSUE THREAD

**Issue by dyun98** [Startlink/BOJ-Feature-Request#96]
ggwp는 제출 매크로라 전체랭킹에서 지워진걸로 아는데 연간랭킹에는 아직 남아있네요ㅜㅜ
그리고 가끔 새로 풀어서 맞은 문제들이 맞은문제에 카운트도지 않던데 왜그런지 잘 모르겠어요,.

**Comment by Baekjoon** [comment]
연/월/주/일 랭킹은 실시간 업데이트가 아니기 때문입니다.

**Comment by Baekjoon** [comment]
ggwp는 연간 랭킹에는 일단 남겨두기로 했습니다.

**Comment by Baekjoon** [comment]
업데이트 예정

https://github.com/Startlink/update-note/blob/master/boj-todo.md
