### ISSUE TITLE
채점이 30분 넘게 92%로 멈춰있습니다.

### ISSUE THREAD

**Issue by alkorang** [Startlink/BOJ-Feature-Request#99]
문제번호 : 1929
채점번호 : 5166711
문제를 제출하고 채점중인 상태에서 채점이 끝날 때까지 기다리고 있었습니다.
그런데 시간제한이 2초인데 30분이 넘게 92%에서 진행이 되지 않습니다.
시간초과인데 잘못 표시되는 것 같아서 재접속을 했는데도 그대로 입니다.
확인부탁드립니다.

**Comment by Baekjoon** [comment]
채점중에서 멈춘 경우 2~3시간 후에 알아서 재채점 됩니다.
